apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-container
  template:
    metadata:
      labels:
        app: django-container
    spec:
      containers:
      - name: django
        image: launathiel/django-kubernetes-project:1.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: user
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        - name: POSTGRES_HOST
          value: postgres-service
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: DEBUG
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: SECRET_KEY
        - name: DJANGO_ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: DJANGO_ALLOWED_HOSTS
        - name: SQL_ENGINE
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: SQL_ENGINE
        - name: SQL_PORT
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: SQL_PORT
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: DATABASE
        - name: EMAIL_HOST_USER
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: EMAIL_HOST_USER
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: EMAIL_HOST_PASSWORD
        volumeMounts:
        - name: django-static
          mountPath: /usr/src/app/static
      volumes:
      - name: django-static
        persistentVolumeClaim:
          claimName: django-pvc